name: home-assistant-escoand
version: 0.47.1snap2
summary: Open-source home automation platform running on Python 3
description: |
  Home Assistant is a home automation platform running on Python 3.
  It is able to track and control all devices at home and offer a
  platform for automating control.

grade: stable
confinement: strict

apps:
  hass:
    command: hass --config $SNAP_DATA --daemon
    daemon: forking
    restart-condition: always
    plugs: [network, network-bind]

parts:
  home-assistant:
    plugin: python
    source: https://github.com/home-assistant/home-assistant.git
    source-tag: 0.47.1
    requirements: requirements_all.txt
    # openzwave build is failing
    prepare: sed -i 's/^python_openzwave/#&/' ../src/requirements_all.txt
