name: home-assistant
version: 0.44.2snap1
summary: Open-source home automation platform running on Python 3
description: |
  Home Assistant is a home automation platform running on Python 3.
  It is able to track and control all devices at home and offer a
  platform for automating control.

grade: devel
confinement: devmode

apps:
  home-assistant:
    command: hass --daemon
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

parts:
  home-assistant:
    plugin: python
    source: https://github.com/home-assistant/home-assistant/archive/0.44.2.tar.gz

  mosquitto:
    plugin: cmake
    source: http://mosquitto.org/files/source/mosquitto-1.4.11.tar.gz
