name: home-assistant
version: 0.44.2snap1
summary: Open-source home automation platform running on Python 3
description: |
  Home Assistant is a home automation platform running on Python 3.
  It is able to track and control all devices at home and offer a
  platform for automating control.

grade: devel
confinement: devmode

apps:
  hass:
    command: hass --config $SNAP_DATA --daemon --skip-pip
    daemon: forking
    restart-condition: always
    plugs: [network, network-bind]

parts:
  home-assistant:
    plugin: python
    source: https://github.com/home-assistant/home-assistant/archive/0.44.2.tar.gz
    python-packages: 
        - aiohttp
        - aiohttp_cors
        - astral
        - async_timeout==1.2.0
        - distro
        - fuzzywuzzy
        - gtts_token
        - mutagen
        - netdisco==1.0.0rc3
        - pytz==2017.2
        - requests
        - sqlalchemy
        - xmltodict
